temp = [22.5, 66.2,33.0,12,21.5,11,12.9]
print(temp)
temp.append(98.2)
print(temp)
temps = temp.pop(2)
print(temps)
print(temp)
max_temp=max(temp)
print(max_temp)
sum_temp = sum(temp)
print(sum_temp)
min_temp = min(temp)
print(min_temp)
avg = sum_temp/len(temp)
print(avg)